import "@repo/ui/globals.css";
import { cn } from "@repo/ui/cn";
import { GeistMono } from "geist/font/mono";
import { GeistSans } from "geist/font/sans";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { Suspense } from "react";
import { ThemeProvider } from "@/components/providers/theme-provider";

const fontSans = GeistSans.variable;
const fontMono = GeistMono.variable;

export const metadata: Metadata = {
  title: "Starter | Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)" },
    { media: "(prefers-color-scheme: dark)" },
  ],
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: {
    locale: (typeof routing.locales)[number];
  };
}

export default async function RootLayout({
  children,
  params: paramsPromise,
}: RootLayoutProps): Promise<React.ReactElement> {
  const params = await paramsPromise;
  const { locale } = params;

  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages({ locale }).catch((error) => {
    console.error("Error loading messages:", error);
    return {};
  });

  return (
    <html lang={locale} suppressHydrationWarning>
      <head />
      <body
        className={cn(
          fontSans,
          fontMono,
          "min-h-screen bg-background font-sans antialiased",
        )}
        suppressHydrationWarning
      >
        <ThemeProvider suppressHydrationWarning>
          <Suspense fallback={"<div></div>Loading...</div>"}>
            <NextIntlClientProvider messages={messages} locale={locale}>
              <div className="relative flex min-h-screen flex-col">
                <div className="flex-1">{children}</div>
              </div>
            </NextIntlClientProvider>
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}
